model:
    name: 'LinearRegressionRULPredictor'
train_test_split:
    name: 'CustomTrainTestSplitter'
    cell_data_path: 'processed_data/Custom'
feature:
    name: 'DischargeModelFeatureExtractor'
    interp_dims: 1000
    critical_cycles:
        - 2
        - 8
        - 9
label:
    name: 'SOHLabelAnnotator'
feature_transformation:
    name: 'ZScoreDataTransformation'
label_transformation:
    name: 'SequentialDataTransformation'
    transformations:
        - name: 'LogScaleDataTransformation'
        - name: 'ZScoreDataTransformation'
